### ISSUE TITLE
Error: Status code 403

### ISSUE THREAD

**Issue by NightMean** [MarcelRobitaille/bbyen#12]
Hey, 
I updated to latest commit yesterday and everything was working perfectly fine upon couple of hours ago. After checking logs I noticed that bbyen is currently stuck on status code 403 and it keeps looping with the same error message. 
Perhaps one of the latest commits broke it? 

```
Sep 05 10:00:49 LinPlex node[22856]: [info] [videos]: Finished checking for new videos {}
Sep 05 10:20:28 LinPlex node[22856]: [info] [videos]: Checking for new videos... {}
Sep 05 10:20:28 LinPlex node[22856]: [verbose] [videos]: Checking channel Aaron (UCcUNYFu8wNDncymesUOtPrg) {}
Sep 05 10:20:28 LinPlex node[22856]: [error] [videos]: Status code 403 {}
Sep 05 10:20:28 LinPlex node[22856]: Error: Status code 403
Sep 05 10:20:28 LinPlex node[22856]:     at ClientRequest.<anonymous> (/opt/YoutubeNotify-bbyen/node_modules/rss-parser/lib/parser.js:88:25)
Sep 05 10:20:28 LinPlex node[22856]:     at Object.onceWrapper (node:events:642:26)
Sep 05 10:20:28 LinPlex node[22856]:     at ClientRequest.emit (node:events:527:28)
Sep 05 10:20:28 LinPlex node[22856]:     at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:631:27)
Sep 05 10:20:28 LinPlex node[22856]:     at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
Sep 05 10:20:28 LinPlex node[22856]:     at HTTPParser.execute (<anonymous>)
Sep 05 10:20:28 LinPlex node[22856]:     at TLSSocket.socketOnData (node:_http_client:494:22)
Sep 05 10:20:28 LinPlex node[22856]:     at TLSSocket.emit (node:events:527:28)
Sep 05 10:20:28 LinPlex node[22856]:     at addChunk (node:internal/streams/readable:315:12)
Sep 05 10:20:28 LinPlex node[22856]:     at readableAddChunk (node:internal/streams/readable:289:9)
Sep 05 10:40:28 LinPlex node[22856]: [info] [videos]: Checking for new videos... {}
Sep 05 10:40:28 LinPlex node[22856]: [verbose] [videos]: Checking channel Aaron (UCcUNYFu8wNDncymesUOtPrg) {}

```

**Comment by MarcelRobitaille** [comment]
Hi @NightMean. This doesn't seem related to the recent changes. If you want to test that, would you check out an older version and try that?

It seems more related to your authentication. Perhaps you hit your quota for the Google API? Could you check the Google dashboard? You could also try moving your Google token and trying to create it again:

```
mv google-credentials.json google-credentials.json.bak
node src/index.js
```

**Comment by NightMean** [comment]
I've recreated the token yesterday. While I do have a lot of subscriptions in the whitelist, I barely scratch the quota with it currently. When I hit the quota previously, I've seen a different message, it was 1 line. 

![image](https://user-images.githubusercontent.com/5726996/188512904-1600ce43-e8ac-4169-9bf2-6579c42cd125.png)

What I find quite strange is that I didn't touch anything and it all started working again. 
It was looping for solid 10 hours. No idea what caused this. 

```
Sep 05 22:00:31 LinPlex node[22856]: Error: Status code 403
Sep 05 22:00:31 LinPlex node[22856]:     at ClientRequest.<anonymous> (/opt/YoutubeNotify-bbyen/node_modules/rss-parser/lib/parser.js:88:25)
Sep 05 22:00:31 LinPlex node[22856]:     at Object.onceWrapper (node:events:642:26)
Sep 05 22:00:31 LinPlex node[22856]:     at ClientRequest.emit (node:events:527:28)
Sep 05 22:00:31 LinPlex node[22856]:     at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:631:27)
Sep 05 22:00:31 LinPlex node[22856]:     at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
Sep 05 22:00:31 LinPlex node[22856]:     at HTTPParser.execute (<anonymous>)
Sep 05 22:00:31 LinPlex node[22856]:     at TLSSocket.socketOnData (node:_http_client:494:22)
Sep 05 22:00:31 LinPlex node[22856]:     at TLSSocket.emit (node:events:527:28)
Sep 05 22:00:31 LinPlex node[22856]:     at addChunk (node:internal/streams/readable:315:12)
Sep 05 22:00:31 LinPlex node[22856]:     at readableAddChunk (node:internal/streams/readable:289:9)
Sep 05 22:20:31 LinPlex node[22856]: [info] [videos]: Checking for new videos... {}
Sep 05 22:20:31 LinPlex node[22856]: [verbose] [videos]: Checking channel Aaron (UCcUNYFu8wNDncymesUOtPrg) {}
Sep 05 22:20:31 LinPlex node[22856]: [verbose] [videos]: Checking channel AeroMobil (UCVekgNuouyp2rpGLMEoWddA) {}
```

**Comment by MarcelRobitaille** [comment]
> What I find quite strange is that I didn't touch anything and it all started working again.

Is it working right now?

It seems like it's related to Google's APIs. I'm not sure if there's anything I can do.

**Comment by NightMean** [comment]
Yes, it is working. 
I guess you are right. It was probably something related to Google's APIs as it started working without any change.
Thanks.
